[package]
name = "rust-plugin-example"
version = "0.1.0"
authors = ["Aram Drevekenin <aram@poor.dev>"]
edition = "2018"

[dependencies]
zellij-tile = "0.41.1"
serde = { version = "1.0", features = ["derive"] }
owo-colors = "3.5.0"
